Adding zsh plugins

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -35,9 +35,12 @@ fi
 
 # Common to Darwin and Linux
 echo "[+] Installing more dev tooling"
+mkdir -p ~/.oh-my-zsh/custom/plugins/
+git clone https://github.com/jeffreytse/zsh-vi-mode ~/.oh-my-zsh/custom/plugins/zsh-vi-mode || echo "[-] Warning: Failed to install zsh-vi-mode"
+git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting || echo "[-] Warning: Failed to install zsh-syntax-highlighting"
+git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions || echo "[-] Warning: Failed to install zsh-autosuggestions"
 
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || echo "[-] Warning: Failed to install ohmyzsh"
-git clone https://github.com/jeffreytse/zsh-vi-mode $ZSH_CUSTOM/plugins/zsh-vi-mode || echo "[-] Warning: Failed to install zsh-vi-mode"
 curl -fsSL https://opencode.ai/install | bash || echo "[-] Warning: Failed to install opencode"
 
 if command -v uv >/dev/null 2>&1; then
